// Auto-generated by OpenLane
module por_dig(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[2:0] otrip,
  input force_pdn,
  input force_ena_rc_osc,
  input force_dis_rc_osc,
  input force_short_oneshot,
  input pwup_filt,
  input osc_ck,
  output osc_ena,
  output[7:0] otrip_decoded,
  output force_pdnb,
  output por_unbuf,
  output startup_timed_out,
  output por_timed_out
);
endmodule
